name: GCP Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: capstone-party2023
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Tambahkan langkah-langkah lain yang Anda butuhkan untuk build, deploy, dan lainnya.
