name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: capstone-party2023
  SERVICE: capstone-party-service
  REGION: asia-southeast1
  IMAGE: your-image-name

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker gcr.io

    - name: Build and push Docker image
      run: |
        docker build -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        credentials: ${{ secrets.GCP_SA_KEY }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE }}:$GITHUB_SHA
        region: ${{ env.REGION }}
        service: ${{ env.SERVICE }}
