name: Deploy API from ML

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          project_id: capstone-party2023
          service: greenix
          region: us-central1
          image: gcr.io/capstone-party2023/greenix:${{ github.sha }}
          flags: '--verbosity debug'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
